### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by BAndonovski** [JetJet13/jetjet-theme-vscode#1]
Hey, great work. Really love the theme you've created. Thanks.  
This is more of a feature request, than an issue report. Aside from vsc, I'm also using Sublime Text 3 and would love it if I can use this there as well.  
Is it possible to port the theme to ST3?

Thanks again :)

**Comment by JetJet13** [comment]
Hey, 

Thanks for showing interest in the JetJet-Theme. I will try and find some time to port the theme to Sublime Text 3 in the near future.

**Comment by JetJet13** [comment]
Hey @BAndonovski, I found some time this weekend and I submitted the theme to Package Control. You can check out [this](https://github.com/wbond/package_control_channel/pull/6303) PR I submitted to add the theme to the library. 

Once it gets merged, it should be available for download and installation. 

Once again, thanks for showing interest in the theme and I hope you get to use the theme in Sublime soon.

Cheers.

**Comment by JetJet13** [comment]
I'll close this once it gets added to the library.

**Comment by BAndonovski** [comment]
Amazing, thank you.

**Comment by JetJet13** [comment]
@BAndonovski , JetJet-Theme is now in Package Control. Here's the [link](https://packagecontrol.io/packages/JetJet%20Color%20Scheme).
Enjoy!
