### ISSUE TITLE
Light markdown lists (markup lists) are hard to read

### ISSUE THREAD

**Issue by andrewsuzuki** [JetJet13/jetjet-theme-vscode#2]
<img width="288" alt="screen shot 2017-11-03 at 11 40 29 am" src="https://user-images.githubusercontent.com/947837/32382536-e9939198-c08b-11e7-911c-d505be7bc19b.png">

**Comment by JetJet13** [comment]
Hey Andrew,

Markdown was something I neglected to test for the light theme. Thanks for bringing this issue up. I'll get on it this weekend.

Cheers.

**Comment by JetJet13** [comment]
Hey Andrew,

I've updated JetJet Theme to fix the markdown syntax highlighting issues for the light theme. Here's what it will look like when you update to `v0.19.1`. 

![jetjet-light-markdown-fix](https://user-images.githubusercontent.com/8130149/32407332-bb110d64-c15d-11e7-8ad8-231fb8c081d2.jpg)

Thanks again for bringing this to my attention,
Cheers.

**Comment by andrewsuzuki** [comment]
Looks great! Thanks -- I've tried hundreds of themes and JetJet Light is definitely one of my favorites.

By the way, what font is that?

**Comment by JetJet13** [comment]
No problem, I'm glad to hear that. 
In regards to the font, this is what I use in vs code
```JSON
    "editor.fontSize": 12,
    "editor.fontFamily": "consolas",
    "editor.fontWeight": "600",
    "editor.lineHeight": 22,
```
