### ISSUE TITLE
What is the fonts in the picture

### ISSUE THREAD

**Issue by DavichiHug** [JetJet13/jetjet-theme-vscode#3]
I really like this theme, can you tell me what font is in the picture?THX 😊
https://github.com/JetJet13/jetjet-theme-vscode/blob/master/images/jetjet/jetjet-js.jpg

**Comment by JetJet13** [comment]
Hey @DavichiHug,

Sorry for the late reply,
I'm glad you like it. The font in that pic is `SF Mono`. It's a font that Apple created for Mac OSX. You will need to look up how to install it because it doesn't come pre-installed.

Cheers.

**Comment by DavichiHug** [comment]
@JetJet13 
Thank you very much for the font you offered！
I use the Windows platform, when I installed the SF Mono font, after selecting this font in VsCode i found it did not change, but in my Microsoft word 2016 is available, can you tell me why? THX

![snipaste_2017-12-06_19-13-56](https://user-images.githubusercontent.com/23614846/33659015-a739fab0-dab9-11e7-8f48-f9fb5508c107.png)

**Comment by JetJet13** [comment]
@DavichiHug ,
I'm not too sure, my best guess would be to restart VS Code so that it can recognize the font. 

Good Luck.

**Comment by DavichiHug** [comment]
you are right ! solved
Thx.
